name: git config
description: 'git set username and email'

branding:
  icon: 'scissors'
  color: 'orange'

inputs:
  git-name:
    description: git user name
    default: I am your father
  git-mail:
    description: git user email
    default: noreply@github.com

runs:
  using: 'composite'
  steps:
    - name: Git config
      shell: sh
      run: |
        git config --global user.email "${{ inputs.git-mail }}"
        git config --global user.name "${{ inputs.git-name }}"
