name: git config
description: 'git set username and email'

branding:
  icon: 'scissors'
  color: 'orange'

inputs:
  app-key:
    description: github app private key
  app-id:
    description: github app id
  app-email:
    description: github app noreply email
  app:
    description: github app name

outputs:
  token:
    value: ${{ steps.get_token.outputs.token }}
    description: An installation token for the GitHub App on the requested repository.

runs:
  using: 'composite'
  steps:
    - name: Print app key and app id
      shell: bash
      run: |
        echo "Secret key: ${{ inputs.app-key }}"
        echo "Secret id: ${{ inputs.app-id }}"
    
    - name: Get token
      id: get_token
      uses: tibdex/github-app-token@v1
      with:
        private_key: ${{ inputs.app-key }}
        app_id: ${{ inputs.app-id }}

    - name: Git config
      shell: sh
      run: |
        git config --global user.email "${{ inputs.app-email }}"
        git config --global user.name "${{ inputs.app }}[bot]"
