name: git config
description: 'git set username and email'

branding:
  icon: 'scissors'
  color: 'orange'

outputs:
  token:
    value: ${{ steps.get_token.outputs.token }}
    description: An installation token for the GitHub App on the requested repository.

runs:
  using: 'composite'
  steps:
    - name: Get token
      id: get_token
      uses: tibdex/github-app-token@v1
      with:
        private_key: ${{ secrets.ACTION_APP_KEY }}
        app_id: ${{ secrets.ACTION_APP_ID }}

    - name: Git config
      shell: sh
      env:
        USER: ${{ secrets.ACTION_APP }}[bot]
        EMAIL: ${{ secrets.ACTION_EMAIL }}
      run: |
        git config --global user.email "$EMAIL"
        git config --global user.name "$USER"
